version: 2.1

orbs:
  slack: circleci/slack@4.4.4

workflows:
  build:
    jobs:
      - validate:
          context:
            - AWS
            - Slack
      - build-base:
          context: Slack
          requires:
            - validate
      - hold-build-base:
          context: Slack
          type: approval
          requires:
            - build-base
      - slack/on-hold:
          mentions: $SLACK_MENTION
          requires:
            - hold-build-base

jobs:
  validate:
    working_directory: ~/project
    docker:
      - image: hashicorp/packer:light
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install AWS Cli
          command: |
            apt-get install curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
      - run:
          name: Run AWS configure
          command: |
            aws configure --profile staging set region $AWS_DEFAULT_REGION
            aws configure --profile staging set access_key $AWS_ACCESS_KEY_ID
            aws configure --profile staging set secret_key $AWS_SECRET_ACCESS_KEY
      - run:
          name: Validate Image
          command: |
            packer fmt aws-ubuntu.pkr.hcl
            packer validate aws-ubuntu.pkr.hcl
      - slack/notify:
          event: fail
          mentions: $SLACK_MENTION
          template: basic_fail_1
  build-base:
    working_directory: ~/project
    docker:
      - image: hashicorp/packer:light
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run:
          name: Build Base
          command: packer build aws-ubuntu.pkr.hcl
      - slack/notify:
          event: fail
          mentions: $SLACK_MENTION
          template: basic_fail_1
      - slack/notify:
          event: pass
          mentions: $SLACK_MENTION
          template: basic_success_1
