version: 2.1

orbs:
  slack: circleci/slack@4.4.4

workflows:
  build:
    jobs:
      - validate:
          context:
            - AWS
            - Slack
      - slack/on-hold:
          mentions: $SLACK_MENTION
          requires:
            - validate
      - hold-build-base:
          context: Slack
          type: approval
          requires:
            - validate
            - slack/on-hold
      - build-base:
          context:
            - AWS
            - Slack
          requires:
            - hold-build-base

jobs:
  validate:
    working_directory: ~/project
    docker:
      - image: tgremlin82/packer_aws:1.0
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Init and Validate Image
          command: |
            packer init aws-ubuntu.pkr.hcl
            packer fmt aws-ubuntu.pkr.hcl
            packer validate aws-ubuntu.pkr.hcl
      - run:
          name: De-Register existing AMI image
          command: aws ec2 deregister-image --image-id ami-07df339ad4f528bf6
      - persist_to_workspace:
          root: .
          paths:
            - .
      - slack/notify:
          event: fail
          mentions: $SLACK_MENTION
          template: basic_fail_1
  build-base:
    working_directory: ~/project
    docker:
      - image: tgremlin82/packer_aws:1.0
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run:
          name: Run AWS configure
          command: |
            aws configure --profile staging set region $AWS_DEFAULT_REGION
            aws configure --profile staging set access_key $AWS_ACCESS_KEY_ID
            aws configure --profile staging set secret_key $AWS_SECRET_ACCESS_KEY
      - run:
          name: Build Base
          command: |
            packer init aws-ubuntu.pkr.hcl
            packer build aws-ubuntu.pkr.hcl
      - slack/notify:
          event: fail
          mentions: $SLACK_MENTION
          template: basic_fail_1
      - slack/notify:
          event: pass
          mentions: $SLACK_MENTION
          template: basic_success_1
